### ISSUE TITLE
Improve quality of search results

### ISSUE THREAD

**Issue by agajdosi** [BlenderKit/platform#12]
Suggestion by Gary Kohime from Discord:

> Can you add the ability to search for ALL words in the search string? As it stands, for example I was looking for a Flag pole and got 3,574 results. I tried a bolean expression, such as Flag AND Pole and got around 8,000 hits. I tried to put the string in quotes and was no help. Here is an screen grab for my example:

![Screenshot 2024-04-15 at 11 46 07](https://github.com/BlenderKit/platform/assets/22000268/f00b7efc-32f9-463f-becf-978cc02a116f)

**Comment by PetrDlouhy** [comment]
@agajdosi Vyhledávání má nyní jinou filozofii. Nepodporujeme žádnou takovou syntaxi, ale assety obsahující obě klíčová slova by to mělo vyhazovat jako první (což se neděje).

Nad případnou změnou logiky vyhledávání bychom se museli pořádně zamyslet. To že ty výsledky úplně neodpovídají očekávání by se možná dalo opravit rovnou.

>@agajdosi Search now has a different philosophy. We don't support any such syntax, but assets containing both keywords should be thrown out first (which is not happening).
>
>We'd have to think hard about changing the search logic, if necessary. The fact that the results don't quite match expectations could perhaps be fixed straight away.

**Comment by agajdosi** [comment]
@PetrDlouhy Yeah, I guess the main problem is that the result does not match what user is expecting. Then they explore if there is any AND operator to precise their results. If the results were precise they would not have need to try and fail on making AND.

This issue is conneted to:
- https://github.com/BlenderKit/BlenderKit-server/issues/676
- https://github.com/BlenderKit/BlenderKit-server/issues/729

**Comment by PetrDlouhy** [comment]
Problém je v tom, že neexistuje žádný asset, který by měl "flag" i "pole" v názvu.
Název hodně boostujeme, takže se na první pozice dostávají assety, které mají v názvu jedno z těch slov. To že by měli to druhé ještě v popisku je už neboostuje tak moc.

**Comment by PetrDlouhy** [comment]
I made the AND operator to have the highest priority now. There seems to be different problem. There are many assets with "flagpole" in tags or description. I will try to address that too, mostly as part of https://github.com/BlenderKit/BlenderKit-server/issues/676

**Comment by PetrDlouhy** [comment]
Now even search for "flag pole" should return assets with "flagpole" on first positions.
I am closing this issue, because I think that big progress was made in this direction.
