### ISSUE TITLE
"Group is being synced" in Newsletter sign up.

### ISSUE THREAD

**Issue by DmytroZern** [BlenderKit/platform#14]
### Bug Description

The newsletter confirmation page that shows after signing up has a "group is being synced..." checkbox field. I suppose it shouldn't be there.

![photo_2024-05-28_12-24-59](https://github.com/BlenderKit/BlenderKit/assets/171021644/49176bc6-f9af-4dc4-8122-7d643c684bc1)

### Steps to Reproduce

1. Create a new account on BlenderKit.com
2. Get redirected to the newsletter confirmation page.

**Comment by agajdosi** [comment]
FYI @PetrDlouhy @radekholy24

**Comment by PetrDlouhy** [comment]
@milano-slesarik Do you know what is going on. I can delete the group, but I don't know how this happened.

@lovaryga @karolinahuserkova Did you create the new group in Sendgrid?

**Comment by karolinahuserkova** [comment]
@PetrDlouhy  no I didn't and I don't think Monika did not also. It's weird if possible I would delete it.

**Comment by PetrDlouhy** [comment]
@milano-slesarik Do you have idea, what is this? I can't even disable/delete it from "Unsubscribe groups".

**Comment by milano-slesarik** [comment]
@PetrDlouhy Webhook `/sendgrid/event-webhook/` takes care of group and global unsubscribes. When request is received, there is `asm_group_id` in the payload (if it's unsubscribe from a particular group, not global). 

Groups from Sendgrid to Blenderkit are being synced using `sync_unsubscribe_groups_to_db` which is (should be) called periodically. That means there is an interval when a new group is in Sendgrid system (if it was created) but not in Blenderkit database. 

During this interval, somebody could theoretically unsubscribe from that group using Sendgrid interface (through email). Webhook then would receive unknown `asm_group_id`. Ignoring it wouldn't be a good idea so the group is created and marked as unsubscribed for this user. 

Then, when `sync_unsubscribe_groups_to_db` is executed again, this group should be completed - its name and other information. Or, if doesn't exist - deleted. 


But I don't understand how come it was created if nobody created new group. 

The only way this can happen is when webhook receives unknown `asm_group_id`. Requests are signed so only Sendgrid can send them.


Need to make sure but I think that there is a bug - such group shouldn't be visible in forms until it's completed.


Can you, please, send me a screenshot of unsub groups table [https://app.sendgrid.com/suppressions/advanced_suppression_manager](https://app.sendgrid.com/suppressions/advanced_suppression_manager)?

And also a screenshot of these groups in BK admin. [https://blenderkit.com/bksecretadmin/sendgrid_integration/unsubscribegroup/](https://blenderkit.com/bksecretadmin/sendgrid_integration/unsubscribegroup/)

![image](https://github.com/BlenderKit/platform/assets/7869582/7072f61c-572f-4ef1-bb20-2a8cefeeeb5f)

This is the `sync_unsubscribe_groups_to_db`:

```
   @classmethod
    def sync_unsubscribe_groups_to_db(cls):
        """sync all unsubscribe groups from SendGrid to the database and
        remove groups that are not in SendGrid anymore"""

        try:
            sendgrid_unsub_groups = SendGridAPIAdapter.get_all_suppression_groups()
        except Exception as e:  # noqa - log the error and reraise e as SendGridAPIAdapterError
            logger.exception("Error fetching unsubscribe groups", exc_info=True)
            raise cls.SendGridServiceError(e) from e

        logger.info("Syncing UnsubscribeGroups from SendGrid...")

        with transaction.atomic():
            for group_data in sendgrid_unsub_groups:
                group, created = UnsubscribeGroup.objects.update_or_create(
                    sendgrid_id=group_data["id"],
                    defaults={
                        "name": group_data["name"],
                        "description": group_data["description"],
                        "unsub_count": group_data["unsubscribes"],
                        "is_default": group_data["is_default"],
                        "last_sync": timezone.now(),
                    },
                )

                if created:
                    logger.info("Created UnsubscribeGroup: %s", group.name)
                else:
                    logger.info("Updated UnsubscribeGroup: %s", group.name)

            # delete groups that are not in SendGrid anymore
            for group in UnsubscribeGroup.objects.exclude(
                sendgrid_id__in=[group_data["id"] for group_data in sendgrid_unsub_groups]
            ):
                group.delete()
                logger.info("Deleted UnsubscribeGroup: %s", group.name)
```

**Comment by PetrDlouhy** [comment]
Screenshot from the admin:
![Snímek obrazovky_2024-06-19_08-37-35](https://github.com/BlenderKit/platform/assets/156755/f51f23b2-c19e-4126-8ed2-f2198c31b60b)

I don't have access to the mailing Sendgrid, please ask @karolinahuserkova

**Comment by karolinahuserkova** [comment]
@PetrDlouhy  we will have a call today with @milano-slesarik

**Comment by karolinahuserkova** [comment]
@PetrDlouhy @milano-slesarik  toto je opravené z toho čo viem, môžem to teda zavrieť?

**Comment by milano-slesarik** [comment]
@karolinahuserkova Áno, ale stále vidím na [https://www.blenderkit.com/profile/settings/](https://www.blenderkit.com/profile/settings/) tú skupinu. Mali by ste ju niekto potom buď označiť ako neaktívnu alebo rovno zavolať tú synchronizáciu skupín, ktorá je tam ako admin action. [Viac info](https://github.com/BlenderKit/BlenderKit-server/pull/881)

**Comment by PetrDlouhy** [comment]
Zkusím to nějak dořešit a zavřít.

**Comment by PetrDlouhy** [comment]
Zavolal jsem tu action, group zmizela.
Zavírám issue.
