### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by Michal251270** [BlenderKit/platform#19]
### Bug Description

Hi
Today I noticed that the content in Blender is very limited. I was reinstaled BlenderKit but with no effect.
### Environment Information - Bug happens on:
- BlenderKit version: v3.12.3.240801
- Blender version and source (blender.org, Steam, Snap, package manager, etc.): v4.1 (from:blender.org )
- Operating system & architecture: Win10 (64), 
- Using VPN, proxy, or firewall? (Yes/No/Not sure, please describe if applicable):No (only Windows Deffender)
![Zrzut ekranu 2024-11-14 125830](https://github.com/user-attachments/assets/8d6fd650-a302-493c-9678-67ee836179b7)
![Zrzut ekranu 2024-11-14 130709](https://github.com/user-attachments/assets/b2bea83a-77ef-465c-b5c1-63f909be4a3a)
![Zrzut ekranu 2024-11-14 130830](https://github.com/user-attachments/assets/f9e9cbf4-8f9a-4785-a602-09635e8c101b)

I have full plan activated.

### Error Logs

there is no error message

### Steps to Reproduce

1. 
2. 
3.

**Comment by Falqo1107** [comment]
I have exactly the same problem. A few hours ago everything was fine. The problem is the same on the website - not all models are displayed there either.

**Comment by Artbytahir** [comment]
I am facing the same issues, there are only 20 scenes that appear. Everything is strange. I have even reinstalled the addon, I have full access.

**Comment by SAURABHINNOCENT** [comment]
I am facing same problem pls resolve it

**Comment by SAURABHINNOCENT** [comment]
![Uploading Screenshot 2024-11-14 175621.png…]()

**Comment by Zafer48gs** [comment]
ı have the same problem. While ı was modelling a bathroom in my laptop ı couldn't find any towel. How it will be solved ?

**Comment by Falqo1107** [comment]
The problem is probably being fixed or is fixing itself. There are more and more models available by the minute.

**Comment by agajdosi** [comment]
Ping @PetrDlouhy

**Comment by PetrDlouhy** [comment]
Sorry for this. Our search index fell out. We were able to fix this within one hour.

**Comment by agajdosi** [comment]
Hello everybody, I am sorry for the inconvenience. Part of our database got corrupted and it needed a complete reindex. Our team knew about the problem since it appeared and the reindex was started quite soon. Originally it could take up to 12 hours for the reindex to finish, but out team was able to run it in parallel and accelerate the process. It should be fine now.

**Comment by PetrDlouhy** [comment]
Now everything should be OK.

**Comment by PetrDlouhy** [comment]
@agajdosi Just to clarify your answer. There never was problem with our database, the data were completely safe all the time. Only the search index was affected.
