### ISSUE TITLE
Long Strings are not wrapped inside .description div on the website [website UI bug]

### ISSUE THREAD

**Issue by Numbian** [BlenderKit/platform#2]
### Describe the bug

Long Strings are not wrapped inside .description div on website
![image](https://github.com/BlenderKit/blenderkit/assets/42476878/1615f2c7-58d1-47ae-a345-de4714e59522)

### Expected behavior

A possible fix could be to add `word-wrap: break-word;` to `.description` in css.

![image](https://github.com/BlenderKit/blenderkit/assets/42476878/2694d40c-2f3b-41cf-85f1-ab08c0141eac)

**Comment by PetrDlouhy** [comment]
This is fixed now.
