### ISSUE TITLE
blenderkit is not working 

### ISSUE THREAD

**Issue by SAURABHINNOCENT** [BlenderKit/platform#20]
I am using blenderkit and ev
![Screenshot 2024-11-14 175621](https://github.com/user-attachments/assets/1c6bfeac-bf94-4c2e-aed3-53e151a2d819)
erthing is showing limited in the assets section, I was working on very important project....

**Comment by agajdosi** [comment]
Hello @SAURABHINNOCENT, we've had an incident with our database. It should be fixed now.

**Comment by agajdosi** [comment]
I am sorry for the problems it caused you, this was an unfortunate and unplanned corruption of the database.

**Comment by PetrDlouhy** [comment]
@agajdosi Just to clarify your answer. There never was problem with our database, the data were completely safe all the time. Only the search index was affected.
