### ISSUE TITLE
Can't see my newly created asset on the blenderkit addon to check if it has been imported correctly.

### ISSUE THREAD

**Issue by Loubardeur** [BlenderKit/platform#21]
### Bug Description

Yesterday, when I tried to check if my assets were properly imported, I didn't see them appear in the add-on the search bar. 

Today I tried to recreate the error with the default cube, but it worked nicely. So, the bug seems to only appear with 3 assets that I either uploaded or reuploaded yesterday.

Plus when I'm on my asset page on blenderkit.com, and I click on "show how users will see the asset" on those 3 buggy assets, it shows either  a error message or shows the description of the default cube that I imported for debuging. (see screanshot below)

![bug report blenderkit](https://github.com/user-attachments/assets/3d277434-8645-477a-94a3-369dbda290bd)
![bug report blenderkit1](https://github.com/user-attachments/assets/7b3c37f9-5526-46b6-9fdf-28600332a715)
![bug report blenderkit2](https://github.com/user-attachments/assets/6883db1d-9f06-459b-9888-629e9401d77d)

### Environment Information - Bug happens on:
- BlenderKit version: v3.12.3 - 240801
- Blender version :  v4.2.1 (from: blender.org)
- Operating system & architecture: Win10 (x86_64)
- Using VPN, proxy, or firewall? : No

### Error Logs

The error seams to be happening on the server side of blenderkit so I don't have any Error logs

### Steps to Reproduce

Like I said I could'nt recreate the error

**Comment by agajdosi** [comment]
FYI (but does not seem urgent): @PetrDlouhy @radekholy24

**Comment by PetrDlouhy** [comment]
I think this problem might be caused by #20.
@Loubardeur Please reopen if there is still problem or you bump into this problem again.
