### ISSUE TITLE
Download assets via a web browser?

### ISSUE THREAD

**Issue by SongCast** [BlenderKit/platform#5]
### Is your feature request related to a problem or weakness of addon? Please describe.

I'm always frustrated when trying download an asset and the integrated BlenderKit interface fails to work. I've been a paying subscriber to BlenderKit for five months and while I greatly appreciate the variety and value of the downloadable assets, with every update to the BlenderKit interface old issues are fixed and new ones introduced, or in the case of BlenderKit 3.1.1, the stalled download "green box of death" has reared its head again. 

When I purchase an online asset from another vendor I never have to wonder how many download attempts I'll have to make, or how many times I'll have to shut down and restart my Blender project, in order to obtain the asset. Unfortunately, this is exactly what happens with BlenderKit.

### Describe the solution you'd like

The option to download BlenderKit assets via a web browser.

### Describe alternatives you've considered

Canceling my BlenderKit subscription.

**Comment by PetrDlouhy** [comment]
Solved also in https://github.com/BlenderKit/blenderkit-team-work/issues/58
