### ISSUE TITLE
Weird asset status

### ISSUE THREAD

**Issue by karolinahuserkova** [BlenderKit/platform#7]
### Bug Description

Again report from Kate White regarding one particular asset from Kanistra Studio:
"This asset has status uploaded, it is visible only to its author." for model that is not mine when logged in and model is not shown when logged out.  
Can't reproduce notification second time.
![blenderkit_2](https://github.com/BlenderKit/blenderkit/assets/104030026/14deb128-235c-4f64-ab09-185389763ff5)

**Comment by PetrDlouhy** [comment]
Not sure how this can happen. Maybe if the asset is freshly validated and not yet indexed ElasticSearch?
That might be fixed in the new gallery, so it is question if it is worth fixing.

**Comment by PetrDlouhy** [comment]
@karolinahuserkova Closing this until we find another case.
